# Generated by Django 5.2.6 on 2025-09-28 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='participants',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
