# Generated by Django 5.2.6 on 2025-09-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_category_item_created_by_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='no', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.category'),
        ),
    ]
